// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBFXwsUx450D5Moyt1UFqa6lfrzf9FGoLI',
    appId: '1:453202429265:web:eb976e1b422a25cba67f70',
    messagingSenderId: '453202429265',
    projectId: 'foodorder-d92ac',
    authDomain: 'foodorder-d92ac.firebaseapp.com',
    storageBucket: 'foodorder-d92ac.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBj2E-PRxHGPKbfTPkCdDqVl6R07ZNrfHg',
    appId: '1:453202429265:android:a2312ef60d7f5027a67f70',
    messagingSenderId: '453202429265',
    projectId: 'foodorder-d92ac',
    storageBucket: 'foodorder-d92ac.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkU2_lVGPS4VlEq5OozTN272_Fm9zW7kY',
    appId: '1:453202429265:ios:9812033a245a58b1a67f70',
    messagingSenderId: '453202429265',
    projectId: 'foodorder-d92ac',
    storageBucket: 'foodorder-d92ac.appspot.com',
    iosBundleId: 'com.example.appFoodorder',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCkU2_lVGPS4VlEq5OozTN272_Fm9zW7kY',
    appId: '1:453202429265:ios:6bab67e6a4a4650ea67f70',
    messagingSenderId: '453202429265',
    projectId: 'foodorder-d92ac',
    storageBucket: 'foodorder-d92ac.appspot.com',
    iosBundleId: 'com.example.appFoodorder.RunnerTests',
  );
}
